version: '3'

services:
  app:
    build: .
    environment:
      DEBUG:
      INTERNAL_IPS:
      DATABASE_URL:
      SECRET_KEY:
      EMAIL_URL:
      DJANGO_ADMINS:
      ORDER_FORM_SEND_EMAIL:
      ORDER_FORM_REPLY_TO_EMAIL:
      GANALYTICS_TRACKING_CODE:
    restart: always
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - ./volumes/static:/opt/services/djangoapp/static
      - ./volumes/media:/opt/services/djangoapp/media

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./volumes/static:/opt/services/djangoapp/static
      - ./volumes/media:/opt/services/djangoapp/media
    depends_on:
      - app

  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
    volumes:
      - "./volumes/db:/var/lib/postgresql/data"
      - "./volumes/pgdata:/tmp"
    ports:
      - "5432:5432"
