version: '3'

services:
  app:
    build: .
    env_file: .env
    environment:
      DEBUG:
      INTERNAL_IPS:
      DATABASE_URL:
      SECRET_KEY:
      EMAIL_URL:
      DJANGO_ADMINS:
      ORDER_FORM_SEND_EMAIL:
      ORDER_FORM_REPLY_TO_EMAIL:
      GANALYTICS_TRACKING_CODE:
    restart: always
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - ./volumes/static:/opt/services/djangoapp/static
      - ./volumes/media:/opt/services/djangoapp/media
    #     - "./webapps/:/app/"

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./volumes/static:/opt/services/djangoapp/static
      - ./volumes/media:/opt/services/djangoapp/media
    depends_on:
      - app

  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
    volumes:
      - "./volumes/db:/var/lib/postgresql/data"
      - "./volumes/pgdata:/tmp"
    ports:
      - "5432:5432"


  mysqldb:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    volumes:
      - "./volumes/mysqldb:/var/lib/mysql"
      - "./volumes/data:/docker-entrypoint-initdb.d" # runs contents on first run
    ports:
      - "3306:3306"

  pgloader:
    image: dimitri/pgloader
    command: pgloader --help
