version: '3'

services:
  app:
    build: .
    environment:
      DEBUG:
      INTERNAL_IPS:
      ALLOWED_HOSTS:
      DATABASE_URL:
      SECRET_KEY:
      EMAIL_URL:
      DJANGO_ADMINS:
      ORDER_FORM_SEND_EMAIL:
      ORDER_FORM_REPLY_TO_EMAIL:
      GANALYTICS_TRACKING_CODE:
    restart: always
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - ./volumes/static:/opt/services/djangoapp/static
      - ./volumes/media:/opt/services/djangoapp/media

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./volumes/static:/opt/services/djangoapp/static
      - ./volumes/media:/opt/services/djangoapp/media
      - ./volumes/certbot:/etc/letsencrypt
    depends_on:
      - app
    # reload configs every 6hrs (in case a new certificate is available)
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
    volumes:
      - "./volumes/db:/var/lib/postgresql/data"
      - "./volumes/pgdata:/tmp"
    ports:
      - "5432:5432"

  certbot:
    depends_on:
      - nginx
    image: certbot/dns-digitalocean
    volumes:
      - ./volumes/certbot:/etc/letsencrypt
    # check cert for renewal every 12 hrs
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # command below sets up certbot with first certificate
    # command: >-
    #   certonly
    #   -n
    #   --dns-digitalocean
    #   --dns-digitalocean-credentials /etc/letsencrypt/digitalocean.ini
    #   --dns-digitalocean-propagation-seconds 120
    #   --email ${CERTBOT_EMAIL}
    #   --agree-tos
    #   --no-eff-email
    #   -d *.${CERTBOT_BASE_URL}
    #   -d ${CERTBOT_BASE_URL}
